config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
   # root :to => "wedding#index"
    resources :wedding
    resources :gallery
    resources :guest do 
      collection do
        post :import
        get :choose
        get :send_mail
      end
    end
    resources :about
    resources :promo
    resources :slide_show_image
	end
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
end

app/models/guest.rb
class Guest < ApplicationRecord

	def self.import(file,wedding_id)
		spreadsheet = Roo::Spreadsheet.open(file.path)
		header = spreadsheet.row(1)
		(2..spreadsheet.last_row).each do |i|
		  row = Hash[[header, spreadsheet.row(i)].transpose]
		  row["wedding_id"] = wedding_id
		  row["guest_id"] = generate_number(row["name"])
		  row["url"] = generate_url wedding_id 
			guest = find_by_id(row["id"]) || new
		  guest.attributes = row.to_hash
		  guest.save!
		end
	end

	def self.generate_initial_name(name)
			split_name = name.split(" ")
			length = split_name.length
			intial_name = split_name[0].first
			1.upto(length-1) do |x|
				intial_name << split_name[x].first
			end
			return intial_name
	end

	def self.generate_url wedding_id
		return CONFIG['url_red']+wedding_id.to_s+"/"+SecureRandom.base64[0..3]
	end

  def self.generate_number(name)
    date = DateTime.now()
		get_partial = []
		get_partial[0] = date.hour.to_s
		get_partial[1] = date.minute.to_s
		get_partial[2] = date.second.to_s

		structure_number = generate_initial_name(name).concat("_")

		get_partial.each do |x|
			structure_number.concat(x)
		end

    check_duplicate_id = Guest.where.not(guest_id:nil).where(guest_id: structure_number)

		if check_duplicate_id.present?
			return generate_number(name)
		else
			return structure_number
		end
  end


end

app/models/promo.rb
class Promo < ApplicationRecord
end

app/models/slide_show_image.rb
class SlideShowImage < ApplicationRecord
  has_attached_file :pic_slideshow, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :pic_slideshow, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/wedding.rb
class Wedding < ApplicationRecord
	has_attached_file :pic_wedding, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :pic_wedding, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/admin/about_controller.rb
class Admin::AboutController < ApplicationController
	layout "admin"

	def index
		@abouts = About.all
	end

	def create
		@about = About.new(description: params[:description], active: params[:active].present? ? true : false)
		if params[:active].present?
			About.update_all active: false
		end
		@about.save
		@abouts = About.all
		respond_to do |f|
			f.js
		end
	end

	def update
		about = About.find_by(id: params[:id])
		if params[:active] == "Active"
			About.update_all active: false
		end
		about.update(description: params[:edit_description_about], active: params[:active] == "Active" ? true : false)
		@abouts = About.all
		respond_to do |f|
			f.js
		end
	end

	def destroy
		about = About.find(params[:id])
		if about.destroy
			respond_to do |f|
				f.html { redirect_to admin_about_index_path }
			end
		else
			respond_to do |f|
				f.html
			end
		end
	end
end

app/controllers/admin/gallery_controller.rb
class Admin::GalleryController < ApplicationController
	layout "admin"

	def index
		@galleries = Gallery.all
	end

	def create
		byebug
	end
end

app/controllers/admin/guest_controller.rb
class Admin::GuestController < ApplicationController
	layout "admin"

	def index
		@weddings = Wedding.all
	end

	def import
		Guest.import(params[:file],params[:wedding].to_i)
		redirect_to admin_guest_index_path, notice: "Guests imported"
	end

	def choose
		@guests = Guest.where(wedding_id:params[:wedding])
		respond_to do |f|
			f.js
		end
	end

	def new
		@guests = Guest.where(wedding_id:params[:wedding_id])
		respond_to do |f|
			f.js
		end
	end

	def send_mail
		guests = Guest.where(wedding_id:params[:wedding_id])
		wedding = Wedding.find_by(id:params[:wedding_id])
		guests.each do |guest|
			UsermailerMailer.send_email_action(guest.email,guest.guest_id,wedding.name_wedding).deliver_now
		end
	end

end

app/controllers/admin/promo_controller.rb
class Admin::PromoController < ApplicationController
  layout "admin"

  def index
    @promos = Promo.all
  end

  def create
    date_start = params[:promo_date_start][:year] + "-" + params[:promo_date_start][:month] + "-" + params[:promo_date_start][:day]
    date_end = params[:promo_date_end][:year] + "-" + params[:promo_date_end][:month] + "-" + params[:promo_date_end][:day]
    @promo = Promo.new(name: params[:name], description: params[:description], promo_date_start: date_start, promo_date_end: date_end, active: params[:active].present? ? true : false)
		if params[:active].present?
			Promo.update_all active: false
    end
    @promo.save
    @promos = Promo.all
		respond_to do |f|
			f.js
		end
  end

  def update
  end

  def destroy
    promo = Promo.find(params[:id])
    if promo.destroy
      respond_to do |f|
        f.html { redirect_to admin_promo_index_path }
      end
    else
      respond_to do |f|
        f.html
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin/gallery_helper.rb
module Admin::GalleryHelper
end

app/helpers/admin/guest_helper.rb
module Admin::GuestHelper
end

app/helpers/admin/promo_helper.rb
module Admin::PromoHelper
end

app/helpers/admin/wedding_helper.rb
module Admin::WeddingHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/admin/_footer.html.erb
<footer>
  <div class="pull-right">
    Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
  </div>
  <div class="clearfix"></div>
</footer>

app/views/layouts/admin/_side_menu.html.erb
<div class="col-md-3 left_col">
  <div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
      <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
    </div>

    <div class="clearfix"></div>

    <!-- menu profile quick info -->
    <div class="profile clearfix">
      <div class="profile_pic">
        <img src="images/img.jpg" alt="..." class="img-circle profile_img">
      </div>
      <div class="profile_info">
        <span>Welcome,</span>
        <h2>John Doe</h2>
      </div>
    </div>
    <!-- /menu profile quick info -->

    <br>

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section active">
        <h3>General</h3>
        <ul class="nav side-menu" style="">
          <li class=""><a><i class="fa fa-home"></i> Master <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu" style="display: none;">
              <li class="current-page"><a href="<%= admin_wedding_index_path %>">Wedding</a></li>
              <li><a href="<%= admin_guest_index_path %>">Guest</a></li>
              <li><a href="<%= admin_about_index_path %>">About</a></li>
              <li><a href="<%= admin_promo_index_path %>">Promo</a></li>
              <li><a href="<%= admin_slide_show_image_index_path %>">Slide Show Image</a></li>
            </ul>
          </li>
          <li><a><i class="fa fa-edit"></i> Kirim Email <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="form.html">General Form</a></li>
              <li><a href="form_advanced.html">Advanced Components</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
    <!-- /sidebar menu -->

    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
      <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="" data-original-title="FullScreen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="" href="login.html" data-original-title="Logout">
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
      </a>
    </div>
    <!-- /menu footer buttons -->
  </div>
</div>

app/views/layouts/admin/_top_navigation.html.erb
<!-- top navigation -->
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <img src="images/img.jpg" alt="">John Doe
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;"> Profile</a></li>
            <li>
              <a href="javascript:;">
                <span class="badge bg-red pull-right">50%</span>
                <span>Settings</span>
              </a>
            </li>
            <li><a href="javascript:;">Help</a></li>
            <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
          </ul>
        </li>

        <li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green">6</span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            <li>
              <a>
                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <div class="text-center">
                <a>
                  <strong>See All Alerts</strong>
                  <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</div>
<!-- /top navigation -->