config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
   # root :to => "wedding#index"
    resources :wedding
    resources :gallery
    resources :guest do 
      collection do
        post :import
        get :choose
        get :send_mail
      end
    end
    resources :about
    resources :promo
    resources :slide_show_image
	end
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
end

app/models/guest.rb
class Guest < ApplicationRecord

	def self.import(file,wedding_id)
		spreadsheet = Roo::Spreadsheet.open(file.path)
		header = spreadsheet.row(1)
		(2..spreadsheet.last_row).each do |i|
		  row = Hash[[header, spreadsheet.row(i)].transpose]
		  row["wedding_id"] = wedding_id
		  row["guest_id"] = generate_number(row["name"])
		  row["url"] = generate_url wedding_id 
			guest = find_by_id(row["id"]) || new
		  guest.attributes = row.to_hash
		  guest.save!
		end
	end

	def self.generate_initial_name(name)
			split_name = name.split(" ")
			length = split_name.length
			intial_name = split_name[0].first
			1.upto(length-1) do |x|
				intial_name << split_name[x].first
			end
			return intial_name
	end

	def self.generate_url wedding_id
		return CONFIG['url_red']+wedding_id.to_s+"/"+SecureRandom.base64[0..3]
	end

  def self.generate_number(name)
    date = DateTime.now()
		get_partial = []
		get_partial[0] = date.hour.to_s
		get_partial[1] = date.minute.to_s
		get_partial[2] = date.second.to_s

		structure_number = generate_initial_name(name).concat("_")

		get_partial.each do |x|
			structure_number.concat(x)
		end

    check_duplicate_id = Guest.where.not(guest_id:nil).where(guest_id: structure_number)

		if check_duplicate_id.present?
			return generate_number(name)
		else
			return structure_number
		end
  end


end

app/models/promo.rb
class Promo < ApplicationRecord
end

app/models/slide_show_image.rb
class SlideShowImage < ApplicationRecord
  has_attached_file :pic_slideshow, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :pic_slideshow, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/wedding.rb
class Wedding < ApplicationRecord
	has_attached_file :pic_wedding, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :pic_wedding, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/admin/about_controller.rb
class Admin::AboutController < ApplicationController
	layout "admin"

	def index
		@abouts = About.all
	end

	def create
		@about = About.new(description: params[:description], active: params[:active].present? ? true : false)
		if params[:active].present?
			About.update_all active: false
		end
		@about.save
		@abouts = About.all
		respond_to do |f|
			f.js
		end
	end

	def update
		about = About.find_by(id: params[:id])
		if params[:active] == "Active"
			About.update_all active: false
		end
		about.update(description: params[:edit_description_about], active: params[:active] == "Active" ? true : false)
		@abouts = About.all
		respond_to do |f|
			f.js
		end
	end

	def destroy
		about = About.find(params[:id])
		if about.destroy
			respond_to do |f|
				f.html { redirect_to admin_about_index_path }
			end
		else
			respond_to do |f|
				f.html
			end
		end
	end
end

app/controllers/admin/gallery_controller.rb
class Admin::GalleryController < ApplicationController
	layout "admin"

	def index
		@galleries = Gallery.all
	end

	def create
		byebug
	end
end

app/controllers/admin/guest_controller.rb
class Admin::GuestController < ApplicationController
	layout "admin"

	def index
		@weddings = Wedding.all
	end

	def import
		Guest.import(params[:file],params[:wedding].to_i)
		redirect_to admin_guest_index_path, notice: "Guests imported"
	end

	def choose
		@guests = Guest.where(wedding_id:params[:wedding])
		respond_to do |f|
			f.js
		end
	end

	def new
		@guests = Guest.where(wedding_id:params[:wedding_id])
		respond_to do |f|
			f.js
		end
	end

	def send_mail
		guests = Guest.where(wedding_id:params[:wedding_id])
		wedding = Wedding.find_by(id:params[:wedding_id])
		guests.each do |guest|
			UsermailerMailer.send_email_action(guest.email,guest.guest_id,wedding.name_wedding).deliver_now
		end
	end

end

app/controllers/admin/promo_controller.rb
class Admin::PromoController < ApplicationController
  layout "admin"

  def index
    @promos = Promo.all
  end

  def create
    date_start = params[:promo_date_start][:year] + "-" + params[:promo_date_start][:month] + "-" + params[:promo_date_start][:day]
    date_end = params[:promo_date_end][:year] + "-" + params[:promo_date_end][:month] + "-" + params[:promo_date_end][:day]
    @promo = Promo.new(name: params[:name], description: params[:description], promo_date_start: date_start, promo_date_end: date_end, active: params[:active].present? ? true : false)
		if params[:active].present?
			Promo.update_all active: false
    end
    @promo.save
    @promos = Promo.all
		respond_to do |f|
			f.js
		end
  end

  def update
  end

  def destroy
    promo = Promo.find(params[:id])
    if promo.destroy
      respond_to do |f|
        f.html { redirect_to admin_promo_index_path }
      end
    else
      respond_to do |f|
        f.html
      end
    end
  end
end

app/controllers/admin/slide_show_image_controller.rb
class Admin::SlideShowImageController < ApplicationController
  layout 'admin'
  def index
    @ssimages = SlideShowImage.all
  end
  
  def create
    @ssimage = SlideShowImage.new(title: params[:title], description: params[:description],  active: params[:active].present? ? true : false, pic_slideshow: params[:pic_slideshow])
    if @ssimage.save
      @ssimages = SlideShowImage.all
      respond_to do |f|
        f.js
        f.html {redirect_to admin_slide_show_image_index_path}
      end
    else
      respond_to do |f|
        f.js
        f.html {redirect_to admin_slide_show_image_index_path}
      end
    end

  end

  def update
  end
  
  def destroy
  end
end

app/controllers/admin/wedding_controller.rb
class Admin::WeddingController < ApplicationController
	layout "admin"

	def index
		@weddings = Wedding.all
	end

	def create
		binding.pry
		if Wedding.create(name_wedding: params[:wedding_name],
			owner: params[:owner],
			pic_wedding:params[:pic_wedding],
			event_date:Date.new(params[:start_date][:year].to_i,params[:start_date][:month].to_i,params[:start_date][:day].to_i)
			)
			@weddings = Wedding.all
			respond_to do |f|
				f.js
				f.html {redirect_to admin_wedding_index_path }
			end
		else
			respond_to do |f|
				f.js
				f.html {redirect_to admin_wedding_index_path }
			end
		end
	end

	def update
		wedding = Wedding.find_by(id:params[:id])
		if wedding.update(name_wedding: params[:edit_wedding_name],
			owner: params[:edit_owner],
			pic_wedding:params[:pic_wedding],
			event_date:Date.new(params[:start_date][:year].to_i,params[:start_date][:month].to_i,params[:start_date][:day].to_i)
			)
			@weddings = Wedding.all
			respond_to do |f|
				f.js
				f.html {redirect_to admin_wedding_index_path }
			end
		else
			respond_to do |f|
				f.js
				f.html {redirect_to admin_wedding_index_path }
			end
		end
	end

	def destroy
		wedding=Wedding.find(params[:id])
		if wedding.destroy
			respond_to do |f|
				f.html { redirect_to admin_wedding_index_path }
			end
		else
			respond_to do |f|
				f.html
			end
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin/gallery_helper.rb
module Admin::GalleryHelper
end

app/helpers/admin/guest_helper.rb
module Admin::GuestHelper
end

app/helpers/admin/promo_helper.rb
module Admin::PromoHelper
end

app/helpers/admin/slide_show_image_helper.rb
module Admin::SlideShowImageHelper
end

app/helpers/admin/wedding_helper.rb
module Admin::WeddingHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/gallery/component/_add_form.html.erb
<div class="row" id="form-add-gallery">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>List wedding <small>Sessions</small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a id='back-to-list' ><i class="fa fa-chevron-left"></i></a></li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
      	<%= form_tag('/admin/gallery', class: 'form-horizontal form-label-left', method:'post', remote:true)  do %>
      		<div class="item form-group">
      			<%= label_tag('image_file_location', 'Location File', class: "control-label col-md-3 col-sm-3 col-xs-12") %>
      			<div class="col-md-6 col-sm-6 col-xs-12">
      				<%= text_field_tag("image_file_location",nil, class: 'form-control')%>
      			</div>
      		</div>
      		<div class="item form-group" >
        		<%= label_tag('image_description', 'Description', class: "control-label col-md-3 col-sm-3 col-xs-12") %>
        		<div class="col-md-6 col-sm-6 col-xs-12">
	        		<%= text_area_tag("owner",nil, class: "form-control") %>
            </div>
        	</div>
          <div class="item form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Active</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <div class="">
                <label>
                  <input type="checkbox" class="js-switch" name="active" value=true checked="checked" /> active
                </label>
              </div>
            </div>
          </div>
          <div class="item form-group" >
            <%= label_tag('owner', 'Owner', class: "control-label col-md-3 col-sm-3 col-xs-12") %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= text_field_tag("owner",nil, class: "form-control") %>
            </div>
          </div>
      		<div class="ln_solid"></div>
      		<div class="form-group">
      			<%= button_tag("Submit", class: "btn btn-primary") %>
      		</div>
      	<% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/gallery/component/_table.html.erb
<table id="data-table" class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Image File Location</th>
			<th>Image Description</th>
			<th>Active</th>
			<th>Create By</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% @galleries.each do |gallery| %>
			<tr>
				<td><%= gallery.image_file_location %></td>
				<td><%= gallery.image_description %></td>
				<td><%= gallery.active %></td>
				<td><%= gallery.create_by %></td>
				<td><a id="<%= gallery.id %>" class="fa fa-edit"></a> || 
					<%= link_to '', admin_gallery_path(gallery.id), class: "fa fa-trash", method: :delete, data: { confirm: 'Are you sure?'}  %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/guest/choose.js.erb
$('#table-guest').html("<%= escape_javascript(render 'admin/guest/component/table.html') %>");

$("#add-guest-aksen").on("click",function(){
	$("#import-guest").show();
	$("#table-guest").hide();	
});

$("#send-email").on("click",function(){
	let id = $("#wedding option:selected").val();
	$.ajax({
		url: '/admin/guest/send_mail',
		method: 'get',
		data: {wedding_id:id}
	});
});

app/views/admin/guest/component/_choose_wedding_guest.html.erb
<div class="row" id="choose-wedding-guest">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>List wedding <small>Sessions</small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a id='back-to-list' ><i class="fa fa-chevron-left"></i></a></li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
      	<%= form_tag( choose_admin_guest_index_path, class: 'form-horizontal form-label-left', method:'get', remote:true)  do %>
      		<div class="item form-group">
      			<%= label_tag('name_wedding', 'Pilih Wedding', class: "control-label col-md-3 col-sm-3 col-xs-12") %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= select_tag("wedding",options_from_collection_for_select(@weddings, "id", "name_wedding"), class: 'form-control')%>
            </div>
      		</div>
      		<div class="ln_solid"></div>
      		<div class="form-group">
      			<%= button_tag("Submit", class: "btn btn-primary") %>
      		</div>
      	<% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/guest/component/_import.html.erb
<div class="row" id="import-guest">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Form Import Guest <small>Sessions</small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><%# link_to new_admin_guest_path, :remote => true do %>
  							<a id="back-import-guest" ><i class="fa fa-chevron-left"></i></a>
							<%# end %>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
      	<%= form_tag('/admin/guest/import', class: 'form-horizontal form-label-left', multipart: true)  do %>
      		<div class="item form-group">
      			<%= label_tag('choose', 'Choose wedding', class: "control-label col-md-3 col-sm-3 col-xs-12") %>
      			<div class="col-md-6 col-sm-6 col-xs-12">
      				<%= select_tag("wedding",options_from_collection_for_select(@weddings, "id", "name_wedding"), class: 'form-control')%>
      			</div>
      		</div>
      		<div class="item form-group" >
        		<%= label_tag('file', 'Upload your file', class: "control-label col-md-3 col-sm-3 col-xs-12") %>
        		<div class="col-md-6 col-sm-6 col-xs-12">
	        		<%= file_field_tag :file, class: "form-control" %>
            </div>
        	</div>
      		<div class="ln_solid"></div>
      		<div class="form-group">
      			<%= button_tag("Submit", class: "btn btn-primary") %>
      		</div>
      	<% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/guest/component/_table.html.erb
<div class="row" id="table-guest-aksen">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>List wedding <small>Sessions</small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a id="add-guest-aksen" ><i class="fa fa-plus-square"></i></a></li>
          <li><a id="send-email"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
	    <div class="x_content" id="reload">
				<table id="data-table" class="table table-striped table-bordered">
					<thead>
						<tr>
							<th>Guest Id</th>
							<th>Name</th>
							<th>Email</th>
							<th>address</th>
							<th>presence</th>
							<th>note</th>
							<th>url</th>
							<th>Wedding Id</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						<% @guests.each do |guest| %>
							<tr>
								<td><%= guest.guest_id %></td>
								<td><%= guest.name %></td>
								<td><%= guest.email %></td>
								<td><%= guest.address %></td>
								<td><%= guest.presence %></td>
								<td><%= guest.note %></td>
								<td><%= guest.url %></td>
								<td><%= guest.wedding_id %></td>
								<td><a id="<%= guest.id %>" class="fa fa-edit"></a> || 
									<%= link_to '', admin_wedding_path(guest.id), class: "fa fa-trash", method: :delete, data: { confirm: 'Are you sure?'}  %></td>
							</tr>
						<% end %>
					</tbody>
				</table>				
      </div>
    </div>
  </div>
</div>

app/views/admin/guest/index.html.erb
<div class="right_col" role="main" style="min-height: 3790px;">
	<div class="">
	  
	  <div class="page-title">
	    <div class="title_left">
	      <h3>Guest</h3>
	    </div>

	    <div class="title_right">
	      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
	        <div class="input-group">
	          <input type="text" class="form-control" placeholder="Search for...">
	          <span class="input-group-btn">
	            <button class="btn btn-default" type="button">Go!</button>
	          </span>
	        </div>
	      </div>
	    </div>
	  </div>

	  <div class="clearfix"></div>
	  
	  <%= render 'admin/guest/component/choose_wedding_guest.html'  %>
	  <div id="table-guest"></div>
	  <%= render 'admin/guest/component/import.html'  %>

	</div>
</div>

app/views/admin/guest/new.js.erb
$("#back-import-guest").on("click",function(){
	$("#import-guest").hide();
	$('#table-guest').html("<%= escape_javascript(render 'admin/guest/component/table.html') %>");
	$('#table-guest').show();	
});

$("#add-guest-aksen").on("click",function(){
	$("#import-guest").show();
	$("#table-guest").hide();	
});

app/views/admin/promo/create.js.erb
alert('success');
$('#name').val('');
$('#description').val('');
$('#promo_date_start').val('');
$('#promo_date_end').val('');
$("#form-add").hide();
$('#reload').html("<%=escape_javascript(render 'admin/promo/component/table.html' )%>");

app/views/admin/promo/index.html.erb
<div class="right_col" role="main" style="min-height: 3790px;">
  <div class="page-title">
    <div class="title_left">
      <h3>Promo</h3>
    </div>

    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div>
      </div>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel"> <!-- Index, show all data from about table -->
        <div class="x_title">
          <h2>Promo List</h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a><i class="fa fa-plus-square" onClick="showForm()"></i></a>
            </li>
          
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content" id="reload">
          <%= render '/admin/promo/component/table' %>
        </div>
      </div>

      <%= render '/admin/promo/component/add_form' %>
      <%= render '/admin/promo/component/edit_form' %>
    </div>
  </div>
</div>

app/views/admin/slide_show_image/component/_add_form.html.erb
<div class="row" id="form-add" style="display:none;">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Add new Slideshow image</h2>
        <div class="clearfix">
      </div>
      <div class="x_content">
        <%= form_tag("/admin/slide_show_image", class: "form-horizontal form-label-left", method: "post", remote:true, multipart: true) do %>
          <div class="item form-group">
            <%= label_tag("title", "Title", class:"control-label col-md-3 col-sm-3 col-xs-12") %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= text_field_tag("title", nil, class: "form-control") %>
            </div>
          </div>
          <div class="item form-group">
            <%= label_tag("description", "Description", class:"control-label col-md-3 col-sm-3 col-xs-12") %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= text_area_tag("description", nil, class: "form-control") %>
            </div>
          </div>
          <div class="item form-group">
            <%= label_tag("active", "Active", class: "control-label col-md-3 col-sm-3 col-xs-12") %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= select_tag("active", options_for_select(["Active", "Inactive"])) %>
            </div>
          </div>
          <div class="item form-group" >
            <%= label_tag('file', 'Upload your image', class: "control-label col-md-3 col-sm-3 col-xs-12") %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= file_field_tag :pic_slideshow, class: "form-control" %>
            </div>
          </div>
          <div class="ln_solid"></div>
      		<div class="form-group">
      			<%= button_tag("Submit", class: "btn btn-primary") %>
      		</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/slide_show_image/component/_table.html.erb
<table id="slideshow_list" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Description</th>
      <th>Image Preview</th>
      <th>Active</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @ssimages.order(:id).each do |ssimage| %>
      <tr>
        <td id="ssimage_id"><%= ssimage.id %></td>
        <td><%= ssimage.title %></td>
        <td><%= ssimage.description %></td>
        <td align="center"><%= image_tag ssimage.pic_slideshow.url(:thumb) %></td>
        <% if ssimage.active %>
          <td><span class="badge badge-success">Active</span></td>
        <% else %>
          <td><span class="badge badge-warning">Inactive</span></td>
        <% end %>
        <td><a id="<%= ssimage.id %>" class="fa fa-edit" onClick="fillEdit(this);"></a> || <%= link_to '', admin_slide_show_image_index_path(ssimage.id), class: "fa fa-trash", method: :delete, data:{confirm: "Are You Sure? "} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/wedding/component/_add_form.html.erb
<div class="row" id="form-add">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>List wedding <small>Sessions</small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a id='back-to-list' ><i class="fa fa-chevron-left"></i></a></li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
      	<%= form_tag('/admin/wedding', class: 'form-horizontal form-label-left', method:'post', remote:true, multipart: true)  do %>
      		<div class="item form-group">
      			<%= label_tag('name_wedding', 'Nama Wedding', class: "control-label col-md-3 col-sm-3 col-xs-12") %>
      			<div class="col-md-6 col-sm-6 col-xs-12">
      				<%= text_field_tag("wedding_name",nil, class: 'form-control')%>
      			</div>
      		</div>
      		<div class="item form-group" >
        		<%= label_tag('owner', 'Pemilik', class: "control-label col-md-3 col-sm-3 col-xs-12") %>
        		<div class="col-md-6 col-sm-6 col-xs-12">
	        		<%= text_field_tag("owner",nil, class: "form-control") %>
            </div>
        	</div>
          <div class="item form-group">
            <%= label_tag('event_date', 'Tanggal Acara', class:"control-label col-md-3 col-xs-12") %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= select_date Date.today, prefix: :start_date, class: "form-control" %>
            </div> 
          </div>
          <div class="item form-group" >
            <%= label_tag('file', 'Upload your image', class: "control-label col-md-3 col-sm-3 col-xs-12") %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= file_field_tag :pic_wedding, class: "form-control" %>
            </div>
          </div>
      		<div class="ln_solid"></div>
      		<div class="form-group">
      			<%= button_tag("Submit", class: "btn btn-primary") %>
      		</div>
      	<% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/wedding/component/_edit_form.html.erb
<div class="row" id="form-edit">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Edit Wedding <small>Sessions</small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a id='back-to-list' ><i class="fa fa-chevron-left"></i></a></li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
      	<%= form_tag('/admin/wedding', class: 'form-horizontal form-label-left', method:'put', remote:true,id: 'edit_form_wedding', multipart:true)  do %>
      		<div class="item form-group">
      			<%= label_tag('edit_name_wedding', 'Nama Wedding', class: "control-label col-md-3 col-sm-3 col-xs-12") %>
      			<div class="col-md-6 col-sm-6 col-xs-12">
      				<%= text_field_tag("edit_wedding_name",nil, class: 'form-control')%>
      			</div>
      		</div>
      		<div class="item form-group" >
        		<%= label_tag('edit_owner', 'Owner', class: "control-label col-md-3 col-sm-3 col-xs-12") %>
        		<div class="col-md-6 col-sm-6 col-xs-12">
	        		<%= text_field_tag("edit_owner",nil, class: "form-control") %>
            </div>
        	</div>
          <div class="item form-group">
            <%= label_tag('event_date', 'Tanggal Acara', class:"control-label col-md-3 col-xs-12") %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= select_date Date.today, prefix: :start_date, class: "form-control" %>
            </div> 
          </div>
          <div class="item form-group" >
            <%= label_tag('file', 'Upload your file', class: "control-label col-md-3 col-sm-3 col-xs-12") %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= file_field_tag :pic_wedding, class: "form-control" %>
            </div>
          </div>
      		<div class="ln_solid"></div>
      		<div class="form-group">
      			<%= button_tag("Submit", class: "btn btn-primary") %>
      		</div>
      	<% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/wedding/component/_table.html.erb
<table id="data-table" class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Nama Wedding</th>
			<th>Owner</th>
			<th>Event Date</th>
			<th>Image</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% @weddings.each do |wedding| %>
			<tr>
				<td><%= wedding.name_wedding %></td>
				<td><%= wedding.owner %></td>
				<td><%= wedding.event_date %></td>
				<td><%= image_tag wedding.pic_wedding.url(:medium) %></td>
				<td><a id="<%= wedding.id %>" class="fa fa-edit"></a> || 
					<%= link_to '', admin_wedding_path(wedding.id), class: "fa fa-trash", method: :delete, data: { confirm: 'Are you sure?'}  %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/wedding/create.js.erb
alert('success');
$('#owner').val('');
$('#wedding_name').val('');
$('#reload').html("<%=escape_javascript(render 'admin/wedding/component/table.html' )%>");